version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - app_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    networks:
      - app_net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - app_net
    depends_on:
      - broker
      - schema-registry
      - kafka-connect
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb:8088

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    container_name: schema-registry
    networks:
      - app_net
    ports:
      - "8086:8081"
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092

  kafka-connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: kafka-connect
    networks:
      - app_net
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8085:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    volumes:
      - $PWD/data:/data

  ksqldb:
    image: confluentinc/ksqldb-server:0.21.0
    container_name: ksqldb
    networks:
      - app_net
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: broker:29092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_STREAMS_PRODUCER_MAX_BLOCK_MS: 9223372036854776000
      KSQL_KSQL_CONNECT_URL: http://kafka-connect:8083
      KSQL_KSQL_SERVICE_ID: confluent_rmoff_01
      KSQL_KSQL_HIDDEN_TOPICS: '^_.*'
  connector-setup:
    image: curlimages/curl:7.87.0
    container_name: connector-setup
    depends_on:
      - kafka-connect
    entrypoint:
      - sh
      - -c
      - |
        echo 'Waiting for Kafka Connect to start...';
        sleep 120;
        echo "Checking Kafka Connect version...";
        curl -v http://kafka-connect:8083/ | grep version;
        echo "Registering PostgreSQL connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/postgres.json \
          -v;
        sleep 20;
        echo "Registering MongoDB hierarchical connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/mongodb-hierarchical-sink.json \
          -v;
        sleep 10;
        echo "Registering Redis connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/redis-sink.json \
          -v;
        sleep 10;
        echo "Registering Elasticsearch connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/elasticsearch-sink.json \
          -v;
        sleep 10;
        echo "Registering Elastic connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/elastic-sink.json \
          -v;
        sleep 10;
        echo "Registering Neo4j connector...";
        curl -X POST http://kafka-connect:8083/connectors \
          -H 'Content-Type: application/json' \
          --data @/connectors/neo4j-sink.json \
          -v;
        sleep 10;
        echo "Checking connector status...";
        curl -v http://kafka-connect:8083/connectors;
    volumes:
      - ./connectors/mongodb-hierarchical-sink.json:/connectors/mongodb-hierarchical-sink.json:ro
      - ./connectors/postgres.json:/connectors/postgres.json:ro
      - ./connectors/elasticsearch-sink.json:/connectors/elasticsearch-sink.json:ro
      - ./connectors/elastic-sink.json:/connectors/elastic-sink.json:ro
      - ./connectors/neo4j-sink.json:/connectors/neo4j-sink.json:ro
      - ./connectors/redis-sink.json:/connectors/redis-sink.json:ro
    networks:
      - app_net

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - app_net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 10

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    networks:
      - app_net
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7474" ]
      interval: 10s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    networks:
      - app_net
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    networks:
      - app_net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 10
  python-script:
    build: ./python-script
    container_name: python-script
    networks:
      - app_net
    depends_on:
      - redis
      - mongo
      - neo4j
      - elasticsearch
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c " echo 'Проверка готовности баз данных...'; wait-for-it postgres:5432 --timeout=0 && wait-for-it mongo:27017 --timeout=0 && wait-for-it redis:6379 --timeout=0 && wait-for-it neo4j:7687 --timeout=0 && wait-for-it elasticsearch:9200 --timeout=0 && echo 'Все БД готовы. Запуск скрипта...'; python ./generate_data.py"

  lab_1:
    build: .
    container_name: lab1
    networks:
      - app_net
    depends_on:
      python-script:
        condition: service_completed_successfully
    ports:
      - "8081:8081"
    command: sh -c "java -jar /app/lab_1-0.0.1-SNAPSHOT.jar"

  lab_2:
    build: ../lab_2
    container_name: lab2
    networks:
      - app_net
    depends_on:
      python-script:
        condition: service_completed_successfully
    ports:
      - "8082:8082"
    command: sh -c "java -jar /app/lab_2-0.0.1-SNAPSHOT.jar"

  lab_3:
    build: ../lab_3
    container_name: lab3
    networks:
      - app_net
    depends_on:
      python-script:
        condition: service_completed_successfully
    ports:
      - "8083:8083"
    command: sh -c "java -jar /app/lab_3-0.0.1-SNAPSHOT.jar"

  gateway:
    build: ../gateway
    container_name: gateway
    networks:
      - app_net
    depends_on:
      python-script:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    command: sh -c "java -jar /app/gateway-0.0.1-SNAPSHOT.jar"

volumes:
  redis-data:
  mongo-data:
  neo4j-data:
  neo4j-logs:
  neo4j-plugins:
  elasticsearch-data:
  postgres-data:
