{
 "title": "Kafka Messages Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Messages Count by Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kafka_consumer\")\n  |> filter(fn: (r) => r._field == \"count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Total Messages by Topic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kafka_consumer\")\n  |> filter(fn: (r) => r._field == \"count\")\n  |> filter(fn: (r) => r.kafka_topic =~ /postgres.public.*/)\n  |> group(columns: [\"kafka_topic\"])\n  |> sum()\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Message Distribution by Topic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kafka_consumer\")\n  |> filter(fn: (r) => r._field == \"count\")\n  |> filter(fn: (r) => r.kafka_topic =~ /postgres.public.*/)\n  |> group(columns: [\"kafka_topic\"])\n  |> sum()\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Topic Message Counts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kafka_consumer\")\n  |> filter(fn: (r) => r._field == \"count\")\n  |> filter(fn: (r) => r.kafka_topic =~ /postgres.public.*/)\n  |> group(columns: [\"kafka_topic\"])\n  |> sum()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}